Update testRigor.yml

diff --git a/.github/workflows/testRigor.yml b/.github/workflows/testRigor.yml
--- a/.github/workflows/testRigor.yml
+++ b/.github/workflows/testRigor.yml
@@ -48,27 +48,27 @@ jobs:
                 echo "Error calling API"
                 exit 1
                 ;;
-            200)
-              # 200: successfully finished
-              echo "Test finished successfully"
-              exit 0
-              ;;
-          227|228)
-            # 227: New - 228: In progress
-            echo "Test is not finished yet"
-            ;;
-          229)
-            # 229: Canceled
-            echo "Test canceled"
-            exit 1
-            ;;
-          230)
-            # 230: Failed
-            echo "Test finished but failed"
-            exit 1
-            ;;
-          *)
-            echo "Unknown status"
-            exit 1
-    esac
-  sleep 10
+              200)
+                # 200: successfully finished
+                echo "Test finished successfully"
+                exit 0
+                ;;
+              227|228)
+                # 227: New - 228: In progress
+                echo "Test is not finished yet"
+                ;;
+              229)
+                # 229: Canceled
+                echo "Test canceled"
+                exit 1
+                ;;
+              230)
+                # 230: Failed
+                echo "Test finished but failed"
+                exit 1
+                ;;
+              *)
+                echo "Unknown status"
+                exit 1
+              esac
+        sleep 10
