Update testRigor.yml

diff --git a/.github/workflows/testRigor.yml b/.github/workflows/testRigor.yml
--- a/.github/workflows/testRigor.yml
+++ b/.github/workflows/testRigor.yml
@@ -29,46 +29,46 @@ jobs:
             --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \
               https://api.testrigor.com/api/v1/apps/26mxW3pa4GnnxLq8b/retest
 
-sleep 10
+          sleep 10
 
-while true
-do
-  echo " "
-  echo "==================================="
-  echo " Checking run status"
-  echo "==================================="
-  response=$(curl -i -o - -s -X GET 'https://api.testrigor.com/api/v1/apps/26mxW3pa4GnnxLq8b/status' -H 'auth-token: 382a7e3a-697e-48e0-8ad0-b710d7c2e98b' -H 'Accept: application/json')
-  code=$(echo "$response" | grep HTTP |  awk '{print $2}')
-  body=$(echo "$response" | sed -n '/{/,/}/p')
-  echo "Status code: " $code
-  echo "Response: " $body
-  case $code in
-    4*|5*)
-      # 400 or 500 errors
-      echo "Error calling API"
-      exit 1
-      ;;
-    200)
-      # 200: successfully finished
-      echo "Test finished successfully"
-      exit 0
-      ;;
-    227|228)
-      # 227: New - 228: In progress
-      echo "Test is not finished yet"
-      ;;
-    229)
-      # 229: Canceled
-      echo "Test canceled"
-      exit 1
-      ;;
-    230)
-      # 230: Failed
-      echo "Test finished but failed"
-      exit 1
-      ;;
-    *)
-      echo "Unknown status"
-      exit 1
+          while true
+          do
+            echo " "
+            echo "==================================="
+            echo " Checking run status"
+            echo "==================================="
+            response=$(curl -i -o - -s -X GET 'https://api.testrigor.com/api/v1/apps/26mxW3pa4GnnxLq8b/status' -H 'auth-token: 382a7e3a-697e-48e0-8ad0-b710d7c2e98b' -H 'Accept: application/json')
+            code=$(echo "$response" | grep HTTP |  awk '{print $2}')
+            body=$(echo "$response" | sed -n '/{/,/}/p')
+            echo "Status code: " $code
+            echo "Response: " $body
+            case $code in
+              4*|5*)
+                # 400 or 500 errors
+                echo "Error calling API"
+                exit 1
+                ;;
+            200)
+              # 200: successfully finished
+              echo "Test finished successfully"
+              exit 0
+              ;;
+          227|228)
+            # 227: New - 228: In progress
+            echo "Test is not finished yet"
+            ;;
+          229)
+            # 229: Canceled
+            echo "Test canceled"
+            exit 1
+            ;;
+          230)
+            # 230: Failed
+            echo "Test finished but failed"
+            exit 1
+            ;;
+          *)
+            echo "Unknown status"
+            exit 1
     esac
   sleep 10
